---
? ''
: octodns:
    cloudflare:
      auto-ttl: true
      proxied: true
  ttl: 300
  type: A
  value: 51.178.2.59
panel:
  octodns:
    cloudflare:
      auto-ttl: true
  ttl: 300
  type: A
  value: 51.254.58.247
www:
  octodns:
    cloudflare:
      auto-ttl: true
      proxied: true
  ttl: 300
  type: A
  value: 51.178.2.59
www2:
  octodns:
    cloudflare:
      auto-ttl: true
      proxied: true
  ttl: 300
  type: A
  value: 51.178.2.59
