---
? ''
: octodns:
    cloudflare:
      auto-ttl: true
  ttl: 300
  type: A
  value: 5.255.91.120
www:
  octodns:
    cloudflare:
      auto-ttl: true
  ttl: 300
  type: CNAME
  value: purenvme.com.
