name: OctoDNS Plan

on:
  # Deploy config whenever DNS changes are pushed to main.
  # push:
  #   branches:
  #     - main
  #   paths:
  #     - '*.yaml'

  pull_request:
  workflow_dispatch:

jobs:
  publish:
    name: OctoDNS before Deploy
    runs-on: ubuntu-20.04
    steps:
      - uses: actions/checkout@v2
      - uses: actions/setup-python@v2
        with:
          python-version: '3.10'
      - run: pip install -r requirements.txt
      - uses: solvaholic/octodns-sync@main
        with:
          config_path: production.yaml
          doit: ''
          add_pr_comment: 'Yes'
          pr_comment_token: ${{ secrets.token }}
        env:
          CLOUDFLARE_ACCOUNT_ID: ${{ secrets.CLOUDFLARE_ACCOUNT_ID }}
          CLOUDFLARE_TOKEN: ${{ secrets.CLOUDFLARE_TOKEN }}